12-21/FND/FND/Controllers/CategoryController.cs
using FND.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FND.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        Entity context = new Entity();  
        //................................................................................................Index
        public IActionResult Index()
        {
            List<Category> deptList = context.Categories.ToList();

            
            return View(deptList);
           
        }
        //................................................................................................New
        public IActionResult New()
        {
            //view="New",Model=null
            return View(new Category());
        }
        //<form method="post">
        [HttpPost]
        public IActionResult SaveNew(Category cat)//Brimitev Type -> if exist -> Storage -> else = Null .
        {
            if (cat.Name != null)
            {
                context.Categories.Add(cat);
                context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();

        }
        //................................................................................................Details
        public IActionResult Details(int id)
        {
            Category cat = context.Categories.FirstOrDefault(d => d.Id == id);
            return View("Details", cat);
        }

        //................................................................................................Delete
        public IActionResult Delete(int id)
        {
            Category? cat = context.Categories.FirstOrDefault(s => s.Id == id);
            context.Categories.Remove(cat);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        //................................................................................................Categories
        public IActionResult Category()
        {
            List<Category> cateModel = context.Categories.ToList();

            return View(cateModel);
        }
        //................................................................................................Sport
        public IActionResult Sport()
        {
            
            List<News> cateModel = context.News.ToList();
            

            return View(cateModel);
        }
        //................................................................................................Political
        public IActionResult Political()
        {
            
            List<News> cateModel = context.News.ToList();
            

            return View(cateModel);
        }

        //................................................................................................Economic
        public IActionResult Economic()
        {
            
            List<News> cateModel = context.News.ToList();
            

            return View(cateModel);
        }
        //................................................................................................Technology
        public IActionResult Technology()
        {
            
            List<News> cateModel = context.News.ToList();
            

            return View(cateModel);
        }
        //................................................................................................Food
        public IActionResult Food()
        {
            
            List<News> cateModel = context.News.ToList();
            

            return View(cateModel);
        }
        //................................................................................................StyleAndBeauty
        public IActionResult StyleAndBeauty()
        {
            
            List<News> cateModel = context.News.ToList();
            

            return View(cateModel);
        }
        //................................................................................................Education
        public IActionResult Education()
        {
            
            List<News> cateModel = context.News.ToList();
            

            return View(cateModel);
        }
        //................................................................................................Crime
        public IActionResult Crime()
        {
            
            List<News> cateModel = context.News.ToList();
            

            return View(cateModel);
        }
    }
}

12-21/FND/FND/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;

namespace FND.Controllers
{
    public class ServicesController : Controller
    {
        IWebHostEnvironment webHostEnvironment;

        public ServicesController(IWebHostEnvironment webHostEnvironment)//injection controller
        {
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult uploadImage()
        {
            return View();
        }
        [HttpPost]//Save
        public IActionResult uploadImage(IFormFile Image)
        {
            if (Image == null || Image.Length == 0)
            {

                return RedirectToAction("New", "News");
            }

            string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "Images");
            string uniqueFileName =  Image.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                Image.CopyTo(fileStream);
                fileStream.Close();
            }


            return RedirectToAction("New", "News");
        }
        
    }
}

12-21/FND/FND/Controllers/UsersController.cs
using FND.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace FND.Controllers
{
    public class UsersController : Controller
    {
        Entity context = new Entity();
        public IActionResult Users()
        {
            
                List<ApplicationUser> AppModel = context.Users.ToList();

                return View(AppModel);
            
        }
        
    }
}

12-21/FND/FND/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FND</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/bootstrap-4.4.1.css" rel="stylesheet" />
    <style>
        .dropdown-menu {
            max-height: 200px;
            overflow-y: auto;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="News" asp-action="AllNews">Welcome @User.Identity.Name</a>
                        </li> 
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (User.Identity.IsAuthenticated == false){
                                 <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                 <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                }
                                else
                                {
                                    @if (User.IsInRole("Admin"))
                                    {
                                        
                                        
                                        <a class="nav-link text-dark" asp-controller="Account" asp-action="AddAdmin">AddAdmin</a>
                                        <a class="nav-link text-dark" asp-controller="Account" asp-action="AddPublisher">AddPublisher</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Users">Users</a>
                                        <a class="nav-link text-dark" asp-controller="roles" asp-action="New">AddRoles</a>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">CategoryControl</a>   
                                    }
                                    @if (User.IsInRole("Admin") || User.IsInRole("Publisher"))
                                    {
                                        <a class="nav-link text-dark" asp-controller="Services" asp-action="uploadImage">UploadImage</a>
                                        <a class="nav-link text-dark" asp-controller="News" asp-action="NewsAdmin">NewsControl</a>
                                        <a class="nav-link text-dark" asp-controller="News" asp-action="New">AddNews</a>
                                        
                                    }
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                   
                                }
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="categoriesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                            <div class="dropdown-menu" aria-labelledby="categoriesDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Sport">Sport</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Political">Political</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Technology">Technology</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Food">Food & Drink</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="StyleAndBeauty">Style & Beauty</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Entertainment">Entertainment</a>
                                
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Crime">Crime</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Education">Education</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Prediction" asp-action="Predict">Predict</a>
                                <!-- Add more categories here container -->
                            </div>
                        </li>
                         
                    </ul>
                    <form class="form-inline my-2 my-lg-0" action="/News/SearchResult" method="get">
                        <input class="form-control mr-sm-2" type="search" name="searchTerm" placeholder="Search" aria-label="Search">
                         <p> - </p>
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                    <p> - </p>
                    <button class="btn btn-outline-success my-2 my-sm-0" onclick="translatePage()">Translate</button>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                </div>
            </div>
        </nav>
    </header>
     <!--class container-->
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/jquery-3.4.1.min.js"></script>
    <script src="~/js/bootstrap-4.4.1.js"></script>
    @await RenderSectionAsync("Scripts", required: false)


   <!-- Hotjar Tracking Code for https://localhost:5028/ -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:5082003,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
<script>
    function translatePage() {
        // Add Google Translate widget dynamically
        var googleTranslateScript = document.createElement('script');
        googleTranslateScript.src = '//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';
        document.body.appendChild(googleTranslateScript);

        // Initialize Google Translate
        window.googleTranslateElementInit = function() {
            new google.translate.TranslateElement({
                pageLanguage: 'ar',
                includedLanguages: 'en,ar', 
                layout: google.translate.TranslateElement.InlineLayout.SIMPLE
            }, 'google_translate_element');
        };

        // Create container for translate widget if not exists
        if (!document.getElementById('google_translate_element')) {
            var div = document.createElement('div');
            div.id = 'google_translate_element';
            document.body.insertBefore(div, document.body.firstChild);
        }
    }
</script>
</body>
</html>